routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
////// Frontend page Routes


Route::get('/', 'HomeController@index')->name('home');
Route::get('/visa/{id}', 'HomeController@visa')->name('visa');
Route::get('/visa_category', 'HomeController@visa_category')->name('visa_category');
Route::get('/tour_packages', 'HomeController@tour')->name('tour');
Route::get('/domastic_tour_packages', 'HomeController@domastic_tour')->name('domastic_tour');
Route::get('/about_us', 'HomeController@about_us')->name('about_us');
Route::get('/arrival_countries', 'HomeController@arrival_countries')->name('arrival_countries');
Route::get('/insaurance', 'HomeController@insaurance')->name('insaurance');
Route::get('/umraah', 'HomeController@umraah')->name('umraah');

///////Search

//Route::get('/search');

///////Search

Route::post('/search-tours', 'HomeController@searchtours')->name('search.tour');
//Route::post('/search-countries/{id}', 'HomeController@searchcountries')->name('search.countries');
//Route::get('/tour', 'TourController@item');


///////Mail

//Route::post('/contact', 'ContactController@store');

Route::get('/tour_packages_detail/{id}', 'HomeController@tour_detail')->name('tour_detail');
Route::get('/domastic_tour_packages_detail', 'HomeController@domastic_tour_detail')->name('domastic_tour_detail');
//Route::post('/contact_us/send', 'HomeController@tour_detail');


Route::get('/contact_us', 'SendEmailController@index')->name('contact_us');
Route::post('/contact_us/send', 'SendEmailController@send');

//Route::get('/tour_packages_detail/{id}', 'SendEmailController@index');
//Route::post('/tour_packages_detail/{id}/send', 'SendEmailController@send');


////// Dashboard page Routes

Route::namespace('Admin')->prefix('admin')->as('admin.')->group(function () {

// Controllers Within The "App\Http\Controllers\Admin" Namespace]

    Route::group(['middleware' => ['admin.guest']], function () {
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('show_login');
        Route::post('login', 'Auth\LoginController@login')->name('login');
    });
    Route::group(['middleware' => ['admin.auth']], function () {

        Route::get('/', 'HomeController@index');
        Route::get('/dashboard', 'HomeController@index');
        Route::get('logout', ['as' => 'auth.logout', 'uses' => 'Auth\LoginController@logout'
        ]);

////// Registration Routes...
//        Route::get('register', ['as' => 'auth.register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
//        Route::post('register', ['as' => 'auth.register', 'uses' => 'Auth\RegisterController@register']);
////
//// Password Reset Routes...
//        Route::get('password/reset/{token?}', ['as' => 'auth.password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
//        Route::post('password/email', ['as' => 'auth.password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
//        Route::get('password/reset', ['as' => 'auth.password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
//        Route::post('password/reset', ['as' => 'auth.password.reset', 'uses' => 'Auth\ResetPasswordController@reset']);


////// Dashboard page Routes
        Route::get('/command/migrate', function () {
            /* php artisan migrate */
            \Artisan::call('migrate');
//            dd("Done");
        });

        Route::resource('contacts', 'ContactController');
        Route::resource('country', 'CountryController');
        Route::resource('home_slider', 'HomeSliderController');
        Route::resource('news', 'NewsController');
        Route::resource('offers', 'OfferController');
        Route::resource('requirments', 'RequirmentsController');
        Route::post('/visa_requirment/fetch/{id}', 'VisaRequirmentController@fetch')->name('visa_requirment');
        Route::resource('visa_requirment', 'VisaRequirmentController');
        Route::resource('testimonials', 'TestimonialController');
        Route::resource('tours', 'TourController');
        Route::resource('tours_images', 'TourImagesController');
        Route::resource('tours_slider', 'TourSliderController');
        Route::resource('tours_videos', 'TourVideoController');
        Route::resource('visa', 'VisaController');
        Route::resource('arrival_countries', 'ArrivalCountriesController');
        Route::resource('insaurance', 'InsauranceController');
        Route::resource('umrah', 'UmrahController');
        Route::resource('domastic', 'DomasticController');


    });
});

app/Tour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tour extends Model
{
    protected $guarded = [];
    public function images(){
        return $this->hasMany(Tour_images::class,'tours_id','id');
    }
}

app/Http/Controllers/Admin/TourController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Tour;
use Illuminate\Http\Request;

class TourController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $adis=Tour::orderBy('id','dec')->get();
        return view('admin.pages.tours.index',compact('adis'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.tours.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'heading'=>'required',
            'cover_url'=>'required',
//            'cover_name'=>'required',
            'price'=>'required',
            'description'=>'required',
            'pkg_includes'=>'required',
            'pkg_exclusive'=>'required',
            'package_title'=>'required',
            'departure_country'=>'required',
            'departure_city'=>'required',
            'min_allowed'=>'required',
            'ticket'=>'required',
            'visa'=>'required',
            'insurance'=>'required',
            'stay'=>'required',
            'hotel'=>'required',
            'company'=>'required',
            'rate_mentioned'=>'required',
            'valid_till'=>'required',
            'posted_on'=>'required',


        ]);

        $date1=date('Y-m-d',strtotime($request->valid_till));
        $date2=date('Y-m-d',strtotime($request->posted_on));

        if ($request->file('cover_url')){
            $file = $this->uploadFile('uploads/tours/',$request->file('cover_url'));
        }
        Tour::create([
            'heading'=>$request->heading,
            'cover_url'=>$file['file_url'],
            'price'=>$request->price,
            'description'=>$request->description,
            'pkg_includes'=>$request->pkg_includes,
            'pkg_exclusive'=>$request->pkg_exclusive,
            'package_title'=>$request->package_title,
            'departure_country'=>$request->departure_country,
            'departure_city'=>$request->departure_city,
            'min_allowed'=>$request->min_allowed,
            'ticket'=>$request->ticket,
            'visa'=>$request->visa,
            'insurance'=>$request->insurance,
            'stay'=>$request->stay,
            'hotel'=>$request->hotel,
            'company'=>$request->company,
            'rate_mentioned'=>$request->rate_mentioned,
            'valid_till'=>$date1,
            'posted_on'=>$date2,
        ]);
        return redirect(route('admin.tours.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tour  $tour
     * @return \Illuminate\Http\Response
     */
    public function show(Tour $tour)
    {
        return view('admin.pages.tours.show',compact('tour'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tour  $tour
     * @return \Illuminate\Http\Response
     */
    public function edit(Tour $tour)
    {
        return view('admin.pages.tours.edit',compact('tour'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tour  $tour
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tour $tour)
    {
        if ($request->file('cover_url')){
            $this->removeFile($tour->cover_url);
            $file = $this->uploadFile('uploads/tours/',$request->file('cover_url'));
            $tour->cover_url=$file['file_url'];
        }

        $tour->heading=$request->heading;
        $tour->price=$request->price;
        $tour->description=$request->description;
        $tour->pkg_includes=$request->pkg_includes;
        $tour->pkg_exclusive=$request->pkg_exclusive;
        $tour->package_title=$request->package_title;
        $tour->departure_country=$request->departure_country;
        $tour->departure_city=$request->departure_city;
        $tour->min_allowed=$request->min_allowed;
        $tour->ticket=$request->ticket;
        $tour->visa=$request->visa;
        $tour->insurance=$request->insurance;
        $tour->stay=$request->stay;
        $tour->hotel=$request->hotel;
        $tour->company=$request->company;
        $tour->rate_mentioned=$request->rate_mentioned;
        $tour->valid_till= date('Y-m-d',strtotime($request->valid_till));
        $tour->posted_on= date('Y-m-d',strtotime($request->posted_on));
        $tour->save();
        return redirect(route('admin.tours.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tour  $tour
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tour $tour)
    {
        $tour->delete();
        return redirect(route('admin.tours.index'));
    }





}

resources/views/admin/pages/tours/edit.blade.php
@extends('admin.layouts.master')
@section('style')
    <style>
        .profile-wrapper{
            display: inline-block !important;
        }
    </style>
    {{--<link rel="stylesheet" href="{{ asset('admin/lib/Hover/style.css') }}">--}}

@endsection
@section('content')
    {{($tour->avatar) }}
    <div class="row profile-wrapper">

        <div class="col-md-6 col-lg-8 profile-right">
            <div class="profile-right-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs nav-justified nav-line">
                    @include('admin.layouts.tab')
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane active" id="activity">

                        <div class="col-sm-8">
                            <div class="panel">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Tours</h4>
                                </div>
                                @if($errors->all())
                                    <div class="alert alert-danget">
                                        @foreach($errors->all() as $error)

                                            <li>{{$error}}</li>

                                        @endforeach
                                    </div>
                                @endif

                                <form method="post" action="{{route('admin.tours.update',$tour->id)}}" enctype="multipart/form-data">
                                    <div class="form">
                                        @method('patch')
                                        @csrf
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <h1 class="panel-title">Heading</h1><br />
                                                <input type="text" name="heading" value="{{$tour->heading}}" placeholder="Heading" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Picture</h1><br />
                                                <div class="container">
                                                    <div class="avatar-upload">
                                                        <div class="avatar-edit">
                                                            <img src="{{ asset($tour->cover_url) }}" width="100px">
                                                        </div><br />
                                                        <div class="avatar-edit">
                                                            <input type='file' value="{{$tour->cover_url}}" name="cover_url" id="imageUpload" accept=".png, .jpg, .jpeg" />
                                                            <label for="imageUpload"></label>
                                                        </div>
                                                        <div class="avatar-preview">
                                                            <div id="imagePreview" style="background-image: url(http://i.pravatar.cc/500?img=7);">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Price</h1><br />
                                                <input type="text" value="{{$tour->price}}" name="price" placeholder="About Us Heading" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Description</h1><br />
                                                <input type="text" value="{{$tour->description}}" name="description" placeholder="Text" class="form-control">
                                            </div>

                                            <div class="form-group">
                                                <h1 class="panel-title">Package Includes</h1><br />
                                                <textarea id="wysiwyg"  name="pkg_includes" placeholder="Package Includes" class="form-control" rows="10">{{$tour->pkg_includes}}</textarea>
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Package Exclusive</h1><br />
                                                <textarea id="wysiwyg" name="pkg_exclusive" placeholder="Package Exclusive" class="form-control" rows="10">{{$tour->pkg_exclusive}}</textarea>
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Package Title</h1><br />
                                                <input type="text" value="{{$tour->package_title}}" name="package_title" placeholder="Package Title" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Departure Country</h1><br />
                                                <input type="text" value="{{$tour->departure_country}}" name="departure_country" placeholder="Departure Country" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Departure City</h1><br />
                                                <input type="text" value="{{$tour->departure_city}}" name="departure_city" placeholder="Departure City" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Min Allowed</h1><br />
                                                <input type="text" value="{{$tour->min_allowed}}" name="min_allowed" placeholder="Min Allowed" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Ticket</h1><br />
                                                <input type="text" value="{{$tour->ticket}}" name="ticket" placeholder="Ticket" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Visa</h1><br />
                                                <input type="text" value="{{$tour->visa}}" name="visa" placeholder="Visa" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Insurance</h1><br />
                                                <input type="text" value="{{$tour->insurance}}" name="insurance" placeholder="Insurance" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Stay</h1><br />
                                                <input type="text" value="{{$tour->stay}}" name="stay" placeholder="Stay" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Hotel</h1><br />
                                                <input type="text" value="{{$tour->hotel}}" name="hotel" placeholder="Hotel" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Company</h1><br />
                                                <input type="text" value="{{$tour->company}}" name="company" placeholder="Company" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">Rate Mentioned</h1><br />
                                                <input type="text" value="{{$tour->rate_mentioned}}" name="rate_mentioned" placeholder="Rate Mentioned" class="form-control">
                                            </div>
                                            <div class="panel-body">
                                                <h1 class="panel-title">Valid Till</h1><br />
                                                <div class="input-group">
                                                    <input type="text" value="{{$tour->valid_till}}" name="valid_till" class="form-control" placeholder="yyyy/mm/dd" id="datepicker">
                                                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                                </div>
                                            </div><div class="panel-body">
                                                <h1 class="panel-title">Posted On</h1><br />
                                                <div class="input-group">
                                                    <input type="text" value="{{$tour->posted_on}}" name="posted_on" class="form-control" placeholder="yyyy/mm/dd" id="datepicker">
                                                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <input class="btn btn-primary" name="submit" type="submit" value="Update" style="margin-left:270px ; width:100px">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/pages/tours/index.blade.php
@extends('admin.layouts.master')
@section('style')
    <style>
        .profile-wrapper{
            display: inline-block !important;
        }
    </style>
@endsection
@section('content')

    <div class="row profile-wrapper">

        <div class="col-md-6 col-lg-8 profile-right">
            <div id="about" class="profile-right-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs nav-justified nav-line">
                    @include('admin.layouts.tab')
                </ul>

                <!-- Tab panes -->

                <div class="container">
                        <h2>Tours Detail</h2>

                    <div class="table-responsive">

                        <table class="table table-responsive table-hover">
                            <thead>
                            <tr>
                                <th>Heading</th>
                                <th>Picture</th>
                                <th>Price</th>
                                <th>Description</th>
                                <th>package Includes</th>
                                <th>package Exclusive</th>
                                <th>Package Title</th>
                                <th>Departure Country</th>
                                <th>Departure City</th>
                                <th>Minimum Allowed</th>
                                <th>Ticket</th>
                                <th>Visa</th>
                                <th>Insurance</th>
                                <th>stay</th>
                                <th>Hotel</th>
                                <th>Company</th>
                                <th>Rate_mentioned</th>
                                <th>Valid_till</th>
                                <th>Posted_on</th>
                                <th>Update</th>
                                <th>Delete</th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach($adis as $adi)
                            <tr>
                                <td>{{$adi->heading}}</td>
                                <td><img src="{{ asset($adi->cover_url) }}" width="100px"></td>
                                <td>{{$adi->price}}</td>
                                <td>{{$adi->description}}</td>
                                <td>{{$adi->pkg_includes}}</td>
                                <td>{{$adi->pkg_exclusive}}</td>
                                <td>{{$adi->package_title}}</td>
                                <td>{{$adi->departure_country}}</td>
                                <td>{{$adi->departure_city}}</td>
                                <td>{{$adi->min_allowed}}</td>
                                <td>{{$adi->ticket}}</td>
                                <td>{{$adi->visa}}</td>
                                <td>{{$adi->insurance}}</td>
                                <td>{{$adi->stay}}</td>
                                <td>{{$adi->hotel}}</td>
                                <td>{{$adi->company}}</td>
                                <td>{{$adi->rate_mentioned}}</td>
                                <td>{{$adi->valid_till}}</td>
                                <td>{{$adi->posted_on}}</td>
                                <td>
                                    <a href="{{route('admin.tours.edit',$adi->id)}}" class="btn btn-info" >Edit</a>
                                </td>
                                <td>
                                    <form action="{{route('admin.tours.destroy', $adi->id)}}" method="post">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" class="btn btn-info" name="delete" style="background-color: #d62728">
                                            Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>

                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>



            </div>
        </div>
    </div>

@endsection