routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
////// Frontend page Routes


Route::get('/', 'HomeController@index')->name('home');
Route::get('/visa/{id}', 'HomeController@visa')->name('visa');
Route::get('/visa_category', 'HomeController@visa_category')->name('visa_category');
Route::get('/tour_packages', 'HomeController@tour')->name('tour');
Route::get('/domastic_tour_packages', 'HomeController@domastic_tour')->name('domastic_tour');
Route::get('/about_us', 'HomeController@about_us')->name('about_us');
Route::get('/arrival_countries', 'HomeController@arrival_countries')->name('arrival_countries');
Route::get('/insaurance', 'HomeController@insaurance')->name('insaurance');
Route::get('/umraah', 'HomeController@umraah')->name('umraah');

///////Search

//Route::get('/search');

///////Search

Route::post('/search-tours', 'HomeController@searchtours')->name('search.tour');
//Route::post('/search-countries/{id}', 'HomeController@searchcountries')->name('search.countries');
//Route::get('/tour', 'TourController@item');


///////Mail

//Route::post('/contact', 'ContactController@store');

Route::get('/tour_packages_detail/{id}', 'HomeController@tour_detail')->name('tour_detail');
Route::get('/domastic_tour_packages_detail', 'HomeController@domastic_tour_detail')->name('domastic_tour_detail');
//Route::post('/contact_us/send', 'HomeController@tour_detail');


Route::get('/contact_us', 'SendEmailController@index')->name('contact_us');
Route::post('/contact_us/send', 'SendEmailController@send');

//Route::get('/tour_packages_detail/{id}', 'SendEmailController@index');
//Route::post('/tour_packages_detail/{id}/send', 'SendEmailController@send');


////// Dashboard page Routes

Route::namespace('Admin')->prefix('admin')->as('admin.')->group(function () {

// Controllers Within The "App\Http\Controllers\Admin" Namespace]

    Route::group(['middleware' => ['admin.guest']], function () {
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('show_login');
        Route::post('login', 'Auth\LoginController@login')->name('login');
    });
    Route::group(['middleware' => ['admin.auth']], function () {

        Route::get('/', 'HomeController@index');
        Route::get('/dashboard', 'HomeController@index');
        Route::get('logout', ['as' => 'auth.logout', 'uses' => 'Auth\LoginController@logout'
        ]);

////// Registration Routes...
//        Route::get('register', ['as' => 'auth.register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
//        Route::post('register', ['as' => 'auth.register', 'uses' => 'Auth\RegisterController@register']);
////
//// Password Reset Routes...
//        Route::get('password/reset/{token?}', ['as' => 'auth.password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
//        Route::post('password/email', ['as' => 'auth.password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
//        Route::get('password/reset', ['as' => 'auth.password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
//        Route::post('password/reset', ['as' => 'auth.password.reset', 'uses' => 'Auth\ResetPasswordController@reset']);


////// Dashboard page Routes
        Route::get('/command/migrate', function () {
            /* php artisan migrate */
            \Artisan::call('migrate');
//            dd("Done");
        });

        Route::resource('contacts', 'ContactController');
        Route::resource('country', 'CountryController');
        Route::resource('home_slider', 'HomeSliderController');
        Route::resource('news', 'NewsController');
        Route::resource('offers', 'OfferController');
        Route::resource('requirments', 'RequirmentsController');
        Route::post('/visa_requirment/fetch/{id}', 'VisaRequirmentController@fetch')->name('visa_requirment');
        Route::resource('visa_requirment', 'VisaRequirmentController');
        Route::resource('testimonials', 'TestimonialController');
        Route::resource('tours', 'TourController');
        Route::resource('tours_images', 'TourImagesController');
        Route::resource('tours_slider', 'TourSliderController');
        Route::resource('tours_videos', 'TourVideoController');
        Route::resource('visa', 'VisaController');
        Route::resource('arrival_countries', 'ArrivalCountriesController');
        Route::resource('insaurance', 'InsauranceController');
        Route::resource('umrah', 'UmrahController');
        Route::resource('domastic', 'DomasticController');


    });
});

resources/views/admin/pages/tours_videos/create.blade.php
@extends('admin.layouts.master')
@section('style')
    <style>
        .profile-wrapper{
            display: inline-block !important;
        }
    </style>
    {{--<link rel="stylesheet" href="{{ asset('admin/lib/Hover/style.css') }}">--}}

@endsection
@section('content')

    <div class="row profile-wrapper">

        <div class="col-md-6 col-lg-8 profile-right">
            <div class="profile-right-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs nav-justified nav-line">
                    @include('admin.layouts.tab')
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane active" id="activity">

                        <div class="col-sm-8">
                            <div class="panel">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Tour Videos</h4>
                                </div>
                                <form method="post" action="{{route('admin.tours_videos.index')}}" enctype="multipart/form-data">
                                    <div class="form">
                                        @csrf
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <h1 class="panel-title">Video Url</h1><br />
                                                <h1 class="panel-title">iframe width="256" height="189"</h1><br />
                                                <input type="text" name="url" placeholder="Url" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <input class="btn btn-primary" name="submit" type="submit" value="Create" style="margin-left:270px ; width:100px">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
{{--<script src="{{ asset('admin/js/style.js') }}"></script>--}}

resources/views/admin/pages/tours_videos/edit.blade.php
@extends('admin.layouts.master')
@section('style')
    <style>
        .profile-wrapper{
            display: inline-block !important;
        }
    </style>
    {{--<link rel="stylesheet" href="{{ asset('admin/lib/Hover/style.css') }}">--}}

@endsection
@section('content')

    <div class="row profile-wrapper">

        <div class="col-md-6 col-lg-8 profile-right">
            <div class="profile-right-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs nav-justified nav-line">
                    @include('admin.layouts.tab')
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane active" id="activity">

                        <div class="col-sm-8">
                            <div class="panel">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Tour Slider</h4>
                                </div>
                                @if($errors->all())
                                    <div class="alert alert-danget">
                                        @foreach($errors->all() as $error)

                                            <li>{{$error}}</li>

                                        @endforeach
                                    </div>
                                @endif

                                <form method="post" action="{{route('admin.tours_videos.update',['tour_videos'=>$tours_video->id])}}" enctype="multipart/form-data">
                                    <div class="form">
                                        @method('patch')
                                        @csrf
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <h1 class="panel-title">Video Url</h1><br />
                                                <input type="text" value="{{($tours_video->url)}}" name="url" placeholder="URL" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <input class="btn btn-primary" name="Update" type="submit" value="Update" style="margin-left:270px ; width:100px">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
{{--<script src="{{ asset('admin/js/style.js') }}"></script>--}}

resources/views/admin/pages/tours_videos/index.blade.php
@extends('admin.layouts.master')
@section('style')
    <style>
        .profile-wrapper{
            display: inline-block !important;
        }
    </style>
@endsection
@section('content')

    <div class="row profile-wrapper">

        <div class="col-md-6 col-lg-8 profile-right">
            <div id="about" class="profile-right-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs nav-justified nav-line">
                    @include('admin.layouts.tab')
                </ul>

                    <div class="container">
                        <h2>Videos</h2>



                        <table class="table table-responsive table-hover">
                            <thead>
                            <tr>
                                <th>Video</th>
                                <th>Update</th>
                                <th>Delete</th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach($adis as $adi)
                            <tr>
                                <td>{{$adi->url}}</td>
                                <td>
                                    <a href="{{route('admin.tours_videos.edit',$adi->id)}}" class="btn btn-info" >Edit</a>
                                </td>
                                <td>
                                    <form action="{{route('admin.tours_videos.destroy', $adi->id)}}" method="post">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" class="btn btn-info" name="delete" style="background-color: #d62728">
                                            Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>

                            @endforeach
                            </tbody>
                        </table>
                    </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/pages/tours_videos/show.blade.php
@extends('admin.layouts.master')
@section('style')
    <style>
        .profile-wrapper{
            display: inline-block !important;
        }
    </style>
@endsection
@section('content')

    <div class="row profile-wrapper">

        <div class="col-md-6 col-lg-8 profile-right">
            <div class="profile-right-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs nav-justified nav-line">
                    @include('admin.layouts.tab')
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane active" id="activity">

                        <div class="col-sm-8">
                            <div class="panel">
                                <div class="panel-heading">
                                    <h4 class="panel-title">About Us</h4>
                                </div>
                                <form>
                                    <div class="form">
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <h1 class="panel-title">MOBILE #</h1><br />
                                                <input type="text" placeholder="Mobile #" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">ADDRESS</h1><br />
                                                <input type="text" placeholder="Address" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">GMAIL</h1><br />
                                                <input type="text" placeholder="Gmail" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">FACEBOOK</h1><br />
                                                <input type="text" placeholder="Facebook" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <h1 class="panel-title">FOOTER TEXT</h1><br />
                                                <input type="text" placeholder="Footer text" class="form-control">
                                            </div>
                                            <div class="form-group">

                                                <input class="btn btn-primary" type="submit" value="Next" style="margin-left:270px ; width:100px">
                                            </div>
                                        </div>

                                    </div>

                                </form>

                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection